### ISSUE TITLE
enode golive

### ISSUE THREAD

**Issue by jubox70** [alastria/alastria-node-besu#11]
Buenos días, dejo el enode completo con la ip pública para el nodo regular de golive: 

enode://9a1db09bc5f28019f3ab9be6d034a7324ea88ed050cc090839e3a14e5469edaffd2a5fc5ee30ca6a7706ea52387da397ee61f082514e8ffe2d1c57a0711cbef6@54.170.111.19:30303

Cualquier cosa me decís. Muchas gracias!!

**Comment by antoniosotomayor** [comment]
Nodo permisionado
