### ISSUE TITLE
Golive ENODE nodo validador

### ISSUE THREAD

**Issue by jubox70** [alastria/alastria-node-besu#12]
Buenas tardes,  soy Ernesto, de golive.

Dejo enode del nuevo nodo validador para permisionado:

enode://747b82c5e2bdfa99852c9cddff318ec31d192c15956fb787d32831832ba3be018f505612ec4d9d4c8543ca3e3c62210cfbb2cc02ae0fd88bc5f5bf3d20e76c56@52.210.11.255:30303

Cualquier cosa me decís.

Muchas gracias!!

**Comment by antoniosotomayor** [comment]
Buenas, Ernesto. Ya está permisionado. Un saludo!
