### ISSUE TITLE
AlastriaB Curl Issue

### ISSUE THREAD

**Issue by profesionaljrm** [alastria/alastria-node-besu#19]
Hi!
Before explaining anything, I have to apologize because I am a bit noobie in everything related to information technology and specially in anything related to blockchain (at least professionally  speaking).
I am trying to deploy an alastria B node so I can test Hyperledger Firefly integration on it.
I have been able (not without issues)  to follow the process to the point where I am supposed to obtain the enode making a CURL request:
curl -X POST --data '{"jsonrpc":"2.0","method":"admin_nodeInfo","params":[],"id":1}' http://127.0.0.1:8545
But I get the following error:
curl: (7) Failed to connect to 127.0.0.1 port 8545 after 0 ms: Connection refused
Not sure what´s wrong here.
Thanks in advance for the help.

**Comment by irzinfante** [comment]
Hello @profesionaljrm
In the compose file you can see that the port binding from the container for the  RPC API is not enabled by default. Try uncommenting this line: https://github.com/alastria/alastria-node-besu/blob/main/docker-compose/docker-compose.yaml#L22
